<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.codeyunze</groupId>
        <artifactId>qof-parent</artifactId>
        <version>17.3.0-SNAPSHOT</version>
    </parent>
    <artifactId>qof-examples</artifactId>
    <name>qof-examples</name>
    <description>QOF 演示工程：Local + MySQL 元数据 + 内置 Web（禁止被业务依赖）</description>
    <dependencies>
        <dependency>
            <groupId>io.github.codeyunze</groupId>
            <artifactId>qof-spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.codeyunze</groupId>
            <artifactId>qof-storage-local</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.codeyunze</groupId>
            <artifactId>qof-storage-cos</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.codeyunze</groupId>
            <artifactId>qof-storage-s3</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.codeyunze</groupId>
            <artifactId>qof-persistence-mysql</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                    <encoding>UTF-8</encoding>
                    <parameters>true</parameters>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>3.5.3</version>
                <configuration>
                    <mainClass>io.github.codeyunze.examples.QofApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
